name: keepalive_kyb

on:
  schedule:
    # 每隔6天运行一次，运行时间点自行设置(此处北京时间8:14运行)
    - cron: '14 0 */6 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Keepalive
      run: python3 koyeb.py
      env:
        KOY_EB: ${{ secrets.KOY_EB }}
